services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: Star_Trek_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 12

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: admin
      DB_PWD: root
      DB_NAME: Star_Trek_DB
      DB_CONNECTION_LIMIT: 20
      ACCESS_TOKEN_SECRET: 331e6ed900670e4097a31179824a9af19172ec339e4d985261f4a71497dee42d356910ebda08560e34fa0482b7a216f6827ddad20a16def2e212f14c75fb21fe
      REFRESH_TOKEN_SECRET: ed40f3792bb581d53e55712edb18cada836cc4d40cb57308540d1d4e8817b7c35018f89ac344ead235e420807129e06bcba4695e4f6ccb5e7b822de9cd68c1bd
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: always
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
      