POST  http://localhost:5000/login
Content-Type: application/json

{
    "username": "Paul"
}

###

POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTcwMzI3MjM1N30.WjAx-n9cmKjhg0jjcVCi8C4qoY3Xo-fncTP8Co-HjxQ"
}

###

GET http://localhost:5000/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTcwMzI3NTE1MCwiZXhwIjoxNzAzMjc2MDUwfQ.6vbqUtte1LU6KYlDHTCEhEB5r1Hd2ReiOD5ypQndSFs

{
    "page": "1",
    "limit": "10"
}