CREATE DATABASE IF NOT EXISTS Star_Trek_DB;
USE Star_Trek_DB;
DROP TABLE IF EXISTS tos;
CREATE TABLE tos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  series VARCHAR(255) NOT NULL,
  season INT NOT NULL,
  episode INT NOT NULL,
  airdate VARCHAR(10) NULL,
  title VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS tng;
CREATE TABLE tng (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  series VARCHAR(255) NOT NULL,
  season INT NOT NULL,
  episode INT NOT NULL,
  airdate VARCHAR(10) NULL,
  title VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS ds9;
CREATE TABLE ds9 (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  series VARCHAR(255) NOT NULL,
  season INT NOT NULL,
  episode INT NOT NULL,
  airdate VARCHAR(10) NULL,
  title VARCHAR(255) NOT NULL,
  link  VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS voy;
CREATE TABLE voy (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  series VARCHAR(255) NOT NULL,
  season INT NOT NULL,
  episode INT NOT NULL,
  airdate VARCHAR(10) NULL,
  title VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS ent;
CREATE TABLE ent (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  series VARCHAR(255) NOT NULL,
  season INT NOT NULL,
  episode INT NOT NULL,
  airdate VARCHAR(10) NULL,
  title VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
